[package]
name = "gameman"
version = "0.1.0"
edition = "2021"

# Stuff used for the examples
[dev-dependencies]
colored = "2.0"
macroquad = "0.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
